---
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Build
        run: |
          echo "Building cheatsheets"
          bash .github/run.sh
          echo "Done"
      - name: Commit and push changes
        continue-on-error: true
        run: |
          git add .
          git commit -m "Update cheatsheets"
          git push
